# Learns faster and is more stable.
_target_: torch.optim.AdamW
_partial_: true

# Tried with 1e-5, but it is way to small 
# I got the best results so far with lr: 1e-4 plus sigma_min: 1e-5 
lr: 1e-4           

weight_decay: 1e-4
betas: [0.9, 0.98]
eps: 1e-8
